#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  case "$(uname -s)" in
    Linux)
      sudo -E aptitude install -y libffi-dev libssl-dev libreadline-dev build-essential zlib1g-dev libxml2-dev libxslt1-dev autoconf automake libtool unzip
      ;;
  esac

  pkg ensure security/mozilla-rootcerts
  if [[ -d "$PKG_HOME/install/etc/openssl/certs" ]]; then
    pushd $PKG_HOME/install/etc/openssl/certs
    if [[ ! -f ".done" ]]; then
      mozilla-rootcerts extract
      mozilla-rootcerts rehash
      touch .done
    fi
    popd
  else
    mozilla-rootcerts install
  fi

  pkg ensure misc/getopt
  pkg ensure net/wget
  pkg ensure www/curl
  pkg ensure devel/gmake
  pkg ensure devel/gettext-tools
}

bootstrap
