#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y libffi-dev libssl-dev libreadline-dev build-essential
      ;;
  esac
}

bootstrap
