#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y libffi-dev libssl-dev libreadline-dev build-essential
      ;;
  esac

  pkg ensure security/mozilla-rootcerts
  mozilla-rootcerts install || true

  pkg ensure misc/getopt
  pkg ensure net/wget
  pkg ensure www/curl
  pkg ensure editors/vim
  pkg ensure devel/git
}

bootstrap
