#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

	for a in getopt wget curl vim git gcc; do
		if [[ ! -x "$(which $a 2>/dev/null || true)" ]]; then
			return 1
		fi
	done

  if [[ -e $PKG_HOME/install/etc/openssl/certs/.done ]]; then
		return 0
	fi

	return 1
}

source sub "$BASH_SOURCE" "$@"
